-- ============================================================================
-- anti-ms-mp — схема Supabase/Postgres (проект yqfdbuiyfkzhkhpiknob, eu-west-1)
-- Снимок для восстановления с нуля. Дамп от 2026-05-29.
-- Ключевая фраза RPC заменена на <<PARSE_KEY_PHRASE>> — реальное значение:
--   ~/anti-ms-mp-secrets (и в .env: см. request_parse/deactivate_query).
-- Восстановление: создать проект Supabase → выполнить этот файл в SQL Editor →
--   залить данные из бэкапа (если есть) или дать парсеру наполнить заново.
-- ============================================================================

-- extensions, нужные функциям presenter_* (digest)
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- ─────────────────────────── ПОСЛЕДОВАТЕЛЬНОСТИ ────────────────────────────
CREATE SEQUENCE IF NOT EXISTS listings_id_seq;
CREATE SEQUENCE IF NOT EXISTS parser_runs_id_seq;

-- ─────────────────────────────── ТАБЛИЦЫ ───────────────────────────────────
CREATE TABLE listings (
  id integer NOT NULL DEFAULT nextval('listings_id_seq'::regclass),
  date date NOT NULL,
  pl text NOT NULL,
  product_id text NOT NULL,
  query text,
  title text NOT NULL,
  url text,
  price integer,
  op integer,
  reg_days integer,
  auth boolean,
  scraped_at timestamptz NOT NULL DEFAULT now(),
  first_seen date,
  last_seen date,
  avito_pay boolean,
  avito_pay_checked_at timestamptz
);

CREATE TABLE parser_runs (
  id bigint NOT NULL DEFAULT nextval('parser_runs_id_seq'::regclass),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL DEFAULT 'running'::text,
  trigger text NOT NULL DEFAULT 'cron'::text,
  host text,
  totals jsonb NOT NULL DEFAULT '{}'::jsonb,
  errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  last_heartbeat timestamptz,
  pid integer,
  hostname text
);

CREATE TABLE monitor_queries (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  query text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  added_by text NOT NULL DEFAULT 'system'::text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_parsed_at timestamptz
);

CREATE TABLE parse_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  query text,
  status text NOT NULL DEFAULT 'pending'::text,
  requested_by text NOT NULL DEFAULT 'dashboard'::text,
  requested_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  note text
);

CREATE TABLE daily_stats (
  day date NOT NULL,
  pl text NOT NULL,
  total integer NOT NULL DEFAULT 0,
  counterfeit integer,
  avito_pay integer,
  avg_disc integer,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ─────────────────────────── ИНДЕКСЫ / КЛЮЧИ ───────────────────────────────
CREATE UNIQUE INDEX daily_stats_pkey ON public.daily_stats USING btree (day, pl);
CREATE INDEX listings_avito_unchecked_idx ON public.listings USING btree (pl, avito_pay) WHERE ((pl = 'avito'::text) AND (avito_pay IS NULL));
CREATE INDEX listings_last_seen_idx ON public.listings USING btree (last_seen DESC);
CREATE UNIQUE INDEX listings_pkey ON public.listings USING btree (id);
CREATE INDEX listings_pl_idx ON public.listings USING btree (pl);
CREATE UNIQUE INDEX listings_pl_product_id_uniq ON public.listings USING btree (pl, product_id);
-- listings_product_id_key (одиночный UNIQUE по product_id) УДАЛЁН 2026-05-31
-- (migr. drop_redundant_listings_product_id_unique_constraint): требовал ГЛОБАЛЬНОЙ
-- уникальности product_id по всем площадкам и ронял upsert при совпадении числового
-- ID между разными маркетплейсами. Верный ключ — составной (pl, product_id) выше.
CREATE UNIQUE INDEX monitor_queries_pkey ON public.monitor_queries USING btree (id);
CREATE UNIQUE INDEX monitor_queries_query_key ON public.monitor_queries USING btree (query);
CREATE INDEX parse_queue_pending_idx ON public.parse_queue USING btree (status, requested_at) WHERE (status = 'pending'::text);
CREATE UNIQUE INDEX parse_queue_pkey ON public.parse_queue USING btree (id);
CREATE UNIQUE INDEX parser_runs_pkey ON public.parser_runs USING btree (id);
CREATE INDEX parser_runs_running_idx ON public.parser_runs USING btree (status, last_heartbeat) WHERE (status = 'running'::text);
CREATE INDEX parser_runs_started_idx ON public.parser_runs USING btree (started_at DESC);
CREATE INDEX parser_runs_status_idx ON public.parser_runs USING btree (status);

-- ──────────────────────── RLS (только чтение публично) ─────────────────────
ALTER TABLE listings        ENABLE ROW LEVEL SECURITY;
ALTER TABLE parser_runs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE monitor_queries ENABLE ROW LEVEL SECURITY;
ALTER TABLE parse_queue     ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_stats     ENABLE ROW LEVEL SECURITY;
-- Запись идёт только через service_role (парсер) и SECURITY DEFINER RPC.
CREATE POLICY daily_stats_read ON daily_stats FOR SELECT TO anon,authenticated USING (true);
CREATE POLICY listings_select_all ON listings FOR SELECT TO anon,authenticated USING (true);
CREATE POLICY monitor_queries_read ON monitor_queries FOR SELECT TO anon,authenticated USING (true);
CREATE POLICY parse_queue_read ON parse_queue FOR SELECT TO anon,authenticated USING (true);
CREATE POLICY parser_runs_public_select ON parser_runs FOR SELECT TO anon,authenticated USING (true);

-- ───────────────────────────── RPC-ФУНКЦИИ ─────────────────────────────────
-- Дашборд дёргает request_parse(фраза, [запрос]) → ставит задачу в parse_queue;
-- queue_poller на VDSina её подхватывает и запускает парсер.
CREATE OR REPLACE FUNCTION public.request_parse(p_secret text, p_query text DEFAULT NULL::text)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  v_secret  text := '<<PARSE_KEY_PHRASE>>';  -- реальное значение в ~/anti-ms-mp-secrets
  v_qid     bigint;
  v_norm    text;
BEGIN
  IF p_secret IS DISTINCT FROM v_secret THEN
    PERFORM pg_sleep(0.5);  -- #30 анти-перебор: задержка только на неверной фразе
    RETURN jsonb_build_object('ok', false, 'error', 'Неверная ключевая фраза');
  END IF;
  v_norm := nullif(btrim(coalesce(p_query, '')), '');
  IF v_norm IS NOT NULL THEN
    INSERT INTO monitor_queries (query, added_by) VALUES (v_norm, 'dashboard')
      ON CONFLICT (query) DO UPDATE SET active = true;
  END IF;
  SELECT id INTO v_qid FROM parse_queue
   WHERE status='pending' AND coalesce(query,'') = coalesce(v_norm,'') LIMIT 1;
  IF v_qid IS NOT NULL THEN
    RETURN jsonb_build_object('ok', true, 'queued', false, 'queue_id', v_qid, 'note', 'Уже в очереди');
  END IF;
  INSERT INTO parse_queue (query, requested_by) VALUES (v_norm, 'dashboard') RETURNING id INTO v_qid;
  RETURN jsonb_build_object('ok', true, 'queued', true, 'queue_id', v_qid,
                            'mode', CASE WHEN v_norm IS NULL THEN 'full' ELSE 'single' END);
END;
$function$;

CREATE OR REPLACE FUNCTION public.deactivate_query(p_secret text, p_query text)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  v_secret text := '<<PARSE_KEY_PHRASE>>';  -- реальное значение в ~/anti-ms-mp-secrets
BEGIN
  IF p_secret IS DISTINCT FROM v_secret THEN
    PERFORM pg_sleep(0.5);  -- #30 анти-перебор: задержка только на неверной фразе
    RETURN jsonb_build_object('ok', false, 'error', 'Неверная ключевая фраза');
  END IF;
  UPDATE monitor_queries SET active = false WHERE query = p_query;
  RETURN jsonb_build_object('ok', FOUND, 'note', CASE WHEN FOUND THEN 'деактивирован' ELSE 'запрос не найден' END);  -- #29
END;
$function$;

-- Примечание: в public-схеме также есть функции presenter_* (presenter_request_headers,
-- presenter_owner_token_hash_from_request, presenter_touch_updated_at) — не относятся
-- к anti-ms-mp (остались от другого функционала проекта Supabase), для восстановления
-- мониторинга не требуются.

-- Удаление запросов мониторинга с дашборда (режим управления, кнопка «−» + «Удалить»).
CREATE OR REPLACE FUNCTION public.remove_queries(p_secret text, p_queries text[], p_delete_cards boolean DEFAULT false)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  v_secret text := '<<PARSE_KEY_PHRASE>>';  -- реальное значение в backup/secrets
  v_qdel int := 0; v_cdel int := 0;
BEGIN
  IF p_secret IS DISTINCT FROM v_secret THEN
    PERFORM pg_sleep(0.5);  -- #30 анти-перебор: задержка только на неверной фразе
    RETURN jsonb_build_object('ok', false, 'error', 'Неверная ключевая фраза');
  END IF;
  IF array_length(p_queries, 1) > 20 THEN  -- #11 анти-массовое-удаление
    RETURN jsonb_build_object('ok', false, 'error', 'Слишком много запросов за раз (макс 20)');
  END IF;
  IF p_queries IS NULL OR array_length(p_queries, 1) IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Список запросов пуст');
  END IF;
  IF p_delete_cards THEN
    DELETE FROM listings WHERE query = ANY(p_queries);
    GET DIAGNOSTICS v_cdel = ROW_COUNT;
  END IF;
  DELETE FROM monitor_queries WHERE query = ANY(p_queries);
  GET DIAGNOSTICS v_qdel = ROW_COUNT;
  RETURN jsonb_build_object('ok', true, 'queries_removed', v_qdel, 'cards_removed', v_cdel);
END;
$function$;
GRANT EXECUTE ON FUNCTION public.remove_queries(text, text[], boolean) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.request_parse(text, text) TO anon, authenticated;       -- #12
GRANT EXECUTE ON FUNCTION public.deactivate_query(text, text) TO anon, authenticated;     -- #12

-- #18: отметки живости (dead-man's switch). Независимый сторож на Oracle (clawbot)
-- читает таблицу (anon, read-only) и алертит в Telegram напрямую, если оркестратор/
-- парсер замолчали. Запись — через record_heartbeat (без фразы; компонент из белого списка).
CREATE TABLE IF NOT EXISTS public.system_heartbeats (
  component  text PRIMARY KEY,
  beat_at    timestamptz NOT NULL DEFAULT now(),
  note       text,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.system_heartbeats ENABLE ROW LEVEL SECURITY;
CREATE POLICY system_heartbeats_read ON public.system_heartbeats FOR SELECT TO anon, authenticated USING (true);

CREATE OR REPLACE FUNCTION public.record_heartbeat(p_component text, p_note text DEFAULT NULL)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
BEGIN
  IF p_component NOT IN ('orchestrator','parser','watchdog') THEN
    RETURN jsonb_build_object('ok', false, 'error', 'unknown component');
  END IF;
  INSERT INTO public.system_heartbeats(component, beat_at, note, updated_at)
  VALUES (p_component, now(), p_note, now())
  ON CONFLICT (component) DO UPDATE SET beat_at = now(), note = EXCLUDED.note, updated_at = now();
  RETURN jsonb_build_object('ok', true, 'component', p_component);
END;
$function$;
GRANT EXECUTE ON FUNCTION public.record_heartbeat(text, text) TO anon, authenticated;
